### ISSUE TITLE
Capstone Project: Feature Request?

### ISSUE THREAD

**Issue by Tereseus** [jsrpy/React_SPA#5]
Hi Justin I have your repo in my queue for a feature request that is to be graded. I do not see the document for the feature request however. Perhaps this is the wrong repo? Each project submitted should be it's own repo and that includes the feature request.

**Comment by jsrpy** [comment]
@Tzuridis It's in the [sub-directory](https://github.com/jsrpy/React_SPA/blob/master/impromptu/impromptu_feature_request.txt). Apologise for the confusion.
